version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: "echo 'db.runCommand({ ping: 1 })' | mongosh --username=${MONGO_USER} --password=${MONGO_PASSWORD} --authenticationDatabase=admin --quiet"
      interval: 5s
      timeout: 5s
      retries: 5

      

  cms:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        DATABASE_URI: ${DATABASE_URI}
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    container_name: cms
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    command: ["sh", "./entrypoint.sh"]

volumes:
  mongo-data:
